### ISSUE TITLE
Error al hacer push.

### ISSUE THREAD

**Issue by bnrey** [aid-austral-2024/tarea2-bnrey#1]
Hola, no estoy pudiendo hacer push de los archivos del repositorio. 
Me da este error 
<img width="694" alt="Captura de pantalla 2024-12-06 a la(s) 1 24 03 p  m" src="https://github.com/user-attachments/assets/1b039e09-f6d3-46f1-919a-d13e39fff7c8">

**Comment by mpru** [comment]
Hola! No he visto este error anteriormente, pero te comparto lo que encontré que comenta la gente en internet. Dicen de probar de nuevo por si es algo de conexión a internet, de probar estando conectado a otra red diferente, y de probar aumentando el tamaño del buffer por si falla al querer pushear mucho contenido junto [(eso está en esta discusión)](https://stackoverflow.com/questions/77856025/git-error-rpc-failed-http-400-curl-22-the-requested-url-returned-error-400-se). Te sugiero que pruebes con esas opciones a ver qué pasa! Aguardamos las novedades.

**Comment by bnrey** [comment]
Hola! encontre que el problema era el  tamaño de los archivos asi que intente cargar el dataset a mano, pero tambien resultaba grande asi que opte por hacer un scrip para achicar el dataset y quedarme con lo que voy a usar, lo grabe en la carpeta datos_curados y ese es el que subi. Gracias igual.
