### ISSUE TITLE
No anda mi app

### ISSUE THREAD

**Issue by bnrey** [aid-austral-2024/tarea2-bnrey#2]
Hola profes!

Hice la prueba de ver lo que cargue hasta ahora en la direccion que figura en el enuncado (https://aid-austral-2024.github.io/tarea2-bnrey/)  y no se ven los graficos interactivos. Yo hice un quarto interactivo con una shiny adentro. 
Si no se podia entregar asi, lo voy a intentar adaptar a una shiny. 
Pero no estoy segura de poder tenerlo listo para esta medianoche.

**Comment by mpru** [comment]
Hola Bárbara! Lo voy a mencionar a @DiegoNOB que tiene más experiencia con Shiny para ver qué te puede comentar, pero yo te adelanto que esto que estas intentando hacer no funciona, porque una shiny depende de un motor de R que procese por detrás, y eso no lo tenemos en GitHub Pages, que se puede usar para mostrar sólo contenido estático. En tu compu sí andaría porque estás corriendo R.

Hay dos opciones: 
1) Más directo con lo que ya tenés armado: hacer la shiny por separado, publicarla en shinyapps.io como habrán visto en clase, incrustar esa web en el documento Quarto con un iframe de html del tipo:

```{=html}
 <iframe id="shiny" src="URL DE LA SHINY" style="border: none; width: 100%; height: 720px" frameborder="0"></iframe>
```
Es decir, eso reemplazaría al código de la shiny.

2) Crear directamente una shiny y toda la info extra que pusiste en el documento Quarto incluirla en la Shiny.

Esperamos la respuesta de Diego y después nos ponemos de acuerdo para que tengas unos días más para adaptar la entrega.

**Comment by DiegoNOB** [comment]
Hola Bárbara! Considero que la solución más rápida a este tema es la siguiente:

Copiá y pegá el código que genera la Shiny en un archivo llamado app.R, y guardalo en el directorio principal de tu repositorio. Por lo que veo en tu `.qmd`, únicamente haría falta que agregues en app.R alguna interfaz para poder ubicar ahí el input de indicadores y los 2 gráficos resultantes. El resto del código, incluida la lectura de datos y demás, ya estaría OK.

Una vez que hagas esto, nosotros podemos ver la shiny sin necesidad de que la subas a un servidor externo o la incrustes con un iframe, directamente ejecutándola mediante la función `runGitHub()` desde nuestras compus.

Avisanos apenas puedas resolverlo, y cualquier otra duda nos avisas.
Saludos!

**Comment by bnrey** [comment]
hola! muchas gracias por sus respuestas.
Perdon la demora en contestar, estoy de viaje por trabajo y me costo mucho
conectarme.
Ahora voy a hacer esto que me dijeron. Yo estuve intentando hacer otras
cosas en el medio, queria agregar mas graficos, pero al intentar agregar
mas cosas se me rompia lo que ya estaba hecho. No le agarre bien la mano
todavia.
Voy a mandarles lo que quedo hecho, aunque no estoy conforme para nada.
Gracias y saludos
Barbara.

**Comment by bnrey** [comment]
Hola, no estoy pudiendo hacer push del archivo con la app. 
Este es el mensaje que me da. 
Intente hacer pull como sugiere pero tambien me da error. 
<img width="682" alt="Captura de pantalla 2024-12-18 a la(s) 7 16 38 p  m" src="https://github.com/user-attachments/assets/d725e9fd-9626-49a2-bed1-4aa12effa507" />

**Comment by DiegoNOB** [comment]
Hola Bárbara! el error indica que tu versión del repositorio "online" (la que está ya subida en GitHub) está más adelantada que tu versión local (la de tu PC). Esto implica que hay cambios en tu repo online que no tenés actualizados en tu compu. Una posible solución es hacer un pull antes del push, aunque primero te aconsejaría revisar qué cambios son los que implementaste, para no perder nada en tu versión local.

Saludos!
Diego

**Comment by mpru** [comment]
Si vos estás segura que el estado actual de tu repo local es el que cuenta y no importa cómo están las cosas en el repo remoto, podés intentar solucionarlo con el comando git push -f
Eso haría que en tu repo remoto quede todo tal como lo tenés actualmente en el local, a la fuerza. No es una acción recomendable cuando se trabaja en grupo pero podría ser la solución.

**Comment by bnrey** [comment]
hola profes,
Gracias por sus respuestas, lo que hice fue cargar el archivo desde git
directamente. Hice antes pull y tambien me tiro error, asi que directamente
lo cargue manualmente. Igualmente voy a intentar entender cual es el error
y solucionarlo.
Ahi puse el archivo app.R con la shiny, sin la introduccion, solo con los
graficos.
